version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fitness_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - fitness-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s

  users-service:
    build: ./users-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: fitness_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fitness-net

  sessions-service:
    build: ./sessions-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: fitness_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fitness-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - users-service
      - sessions-service
    networks:
      - fitness-net

networks:
  fitness-net:
    driver: bridge