apiVersion: v1
kind: ServiceAccount
metadata:
  name: sessions-service-account
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: sessions-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sessions-service-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sessions-service-account
  namespace: default
roleRef:
  kind: Role
  name: sessions-service-role
  apiGroup: rbac.authorization.k8s.io

